baseurl: /files/archive/spec/2.11
safe: true
lsi: false
highlighter: null
markdown: redcarpet
encoding: utf-8
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript", "footnotes"]
